name: Deploy to Heroku

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - name: Run tests
        run: npm test
        env:
          MONGO_USER: 'ads-heroku-user'
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_CLUSTER_URL: 'ads-mongo-cluster.2amnt.mongodb.net'
          MONGO_DB_NAME: 'ads-heroku-db'
          MONGO_COLLECTION_NAME: 'ads-ci-test'

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: wojteks27@gmail.com
          heroku_app_name: ads-tracker-cldnry
